---

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always

# BEGIN
rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem
# END